# Generated by Django 3.0.4 on 2020-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
